name: my workflow file2
on :
   push:
    branches:
     -  main
   pull_request:
     branches:
       - main

env:
  ENV_TYPE: DEV
  APP_USER: KB
  APP_PORT: 80
jobs:
  job1: 
     name: JOB1
     runs-on: ubuntu-latest
     steps:
      - name: step1
        run : |
              pwd
              ls -ltr
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Step-3
        run : |
         echo `pwd` >> myartifact.txt
              ls -ltr
      - name: upload single file
        uses: actions/upload-artifact@v5.0.0
        with: 
          name: single_file
          path: ./myartifact.txt
  job2: 
     name: JOB2
     needs: job1
     runs-on: ubuntu-latest
     steps:
      - name: checkign current directory
        run : |
              pwd
              ls -ltr
      - name: download single artifact
        uses: actions/download-artifact@v5.0.0
        with:
          name: single_file
      - name: checkign current directory
        run : |
              pwd
              ls -ltr
  job3: 
     name: JOB3
     needs: job1
     runs-on: ubuntu-latest
     steps:
      - name: creating custom folder for download
        run : mkdir -p single_file
      - name: checkign current directory
        run : |
              pwd
              ls -ltr
      - name: download single artifact
        uses: actions/download-artifact@v5.0.0
        with:
          name: single_file
          path: single_file
      - name: checkign current directory
        run : |
              pwd
              ls -ltr single_file
      - name: check block
        run : exit 0
      - name: Referring environment variables
        run : |
              echo "[Info] running deployment for $ENV_TYPE with user $APP_USER"
              echo "[Info] Once deployment is doen, app pot $APP_PORT is open"
      - name: Referring to the secrets
        run : |
              echo "[Info] the application password is ${{ secrets.APP_PSWRD }}
              echo "[Info] referred secrets"
         
